platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
  - name: todo-api

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd todo-api
    dotnet publish
    cp -r obj/Debug/netcoreapp2.0  ../build-output